TARGET_ROLES = [
    "Application Support Engineer",
    "Production Support Engineer",
    "Technical Support Engineer",
    "Cloud Support Engineer",
    "Cloud Operations Engineer",
    "Operations Engineer",
    "Site Reliability Engineer",
    "SRE",
    "DevOps Engineer",
    "Junior DevOps Engineer",
    "Cloud Engineer",
    "Production Operations Engineer",
    "Application Operations Engineer",
    "Technical Operations Engineer",
]

SKILLS = [
    "GCP",
    "Google Cloud",
    "AWS",
    "Azure",
    "Linux",
    "Python",
    "Java",
    "SQL",
    "REST API",
    "API Testing",
    "ServiceNow",
    "New Relic",
    "NRQL",
    "Postman",
    "Docker",
    "Kubernetes",
    "Git",
    "CI/CD",
    "DevOps",
    "SRE",
    "Production Support",
    "Application Support",
    "Incident Management",
    "Root Cause Analysis",
    "Log Analysis",
    "System Monitoring",
    "Application Monitoring",
]

LOCATIONS = [
    "Chennai",
    "Bangalore",
    "Hyderabad",
    "Remote",
  "Coimbatore",
]

EXPERIENCE_YEARS = 1.5
