name: Daily Job Agent

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * *"

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Run automation
        run: python jobs/daily_test.py
